source :rubygems

gem "fluent-config-regexp-type", "1.0.0"
gem "fluent-logger", "0.9.0"
gem "fluent-plugin-aws-elasticsearch-service", "2.4.1"
gem "fluent-plugin-dogstatsd", "0.0.6"
gem "fluent-plugin-elasticsearch", "< 6"
gem "fluent-plugin-kafka", "0.16.3"
gem "fluent-plugin-kubernetes_metadata_filter", "2.7.1"
gem "fluent-plugin-multi-format-parser", "1.0.0"
gem "fluent-plugin-prometheus", "1.8.5"
gem "fluent-plugin-record-modifier", "2.1.0"
gem "fluent-plugin-rewrite-tag-filter", "2.4.0"
gem "fluent-plugin-s3", "1.6.0"
gem "fluent-plugin-systemd", "1.0.5"
gem "fluent-plugin-td", "1.1.0"
gem "fluent-plugin-td-monitoring", "0.2.4"
gem "fluent-plugin-webhdfs", "1.4.0"
gem "fluentd", "1.13.2"
