source :rubygems

gem "fluent-config-regexp-type", "1.0.0"
gem "fluent-logger", "0.8.0"
gem "fluent-plugin-aws-elasticsearch-service", "2.4.0"
gem "fluent-plugin-dogstatsd", "0.0.6"
gem "fluent-plugin-elasticsearch", "< 5"
gem "fluent-plugin-kafka", "0.9.2"
gem "fluent-plugin-kubernetes_metadata_filter", "2.5.2"
gem "fluent-plugin-multi-format-parser", "1.0.0"
gem "fluent-plugin-prometheus", "1.3.0"
gem "fluent-plugin-record-modifier", "2.0.1"
gem "fluent-plugin-rewrite-tag-filter", "2.1.1"
gem "fluent-plugin-s3", "1.1.9"
gem "fluent-plugin-systemd", "1.0.2"
gem "fluent-plugin-td", "1.0.0"
gem "fluent-plugin-td-monitoring", "0.2.4"
gem "fluent-plugin-webhdfs", "1.2.3"
gem "fluentd", "1.4.2"
